topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400
  ad_master_2client: &ad_master_2client
    name: ad_master_2client
    cpu: 4
    memory: 12000
  ad_root_child_tree_master_1client: &ad_root_child_tree_master_1client
    name: ad_root_child_tree_master_1client
    cpu: 4
    memory: 12000
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 2
    memory: 2400

jobs:
  fedora-latest/build:
    requires: []
    priority: 150
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-latest
          name: freeipa/ci-master-f31
          version: 0.0.2
        timeout: 1800
        topology: *build

  fedora-latest/test_trust:
    requires: [fedora-latest/build]
    priority: 100
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py
        template: *ci-master-latest
        timeout: 7200
        topology: *ad_root_child_tree_master_1client
