#
# Template for temporary test commit
#
# $ ln -sf ipatests/prci_definitions/temp_commit.yaml .freeipa-pr-ci.yaml
#

topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_3client: &master_3client
    name: master_3client
    cpu: 5
    memory: 10150
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 2
    memory: 2400
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 10150
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 12900
  ad_master_2client: &ad_master_2client
    name: ad_master_2client
    cpu: 4
    memory: 12000
  ad_master: &ad_master
   name: ad_master
   cpu: 4
   memory: 12000
  adroot_adchild_adtree_master_1client: &adroot_adchild_adtree_master_1client
    name: adroot_adchild_adtree_master_1client
    cpu: 8
    memory: 14500


jobs:
  fedora-27/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f27
          name: freeipa/ci-ipa-4-6-f27
          version: 1.0.3
        timeout: 1800
        topology: *build

  fedora-27/test_crlgen_manage:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_crlgen_manage.py
        template: *ci-master-f27
        timeout: 3600
        topology: *master_1repl

  fedora-27/nfs:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_nfs.py
        template: *ci-master-f27
        timeout: 9000
        topology: *master_2repl_1client

  fedora-27/test_server_del:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_server_del.py
        template: *ci-master-f27
        timeout: 10800
        topology: *master_2repl_1client

  fedora-27/test_installation_TestInstallWithCA_KRA1:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA_KRA1
        template: *ci-master-f27
        timeout: 10800
        topology: *master_3repl_1client

  fedora-27/test_installation_TestInstallWithCA_KRA2:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA_KRA2
        template: *ci-master-f27
        timeout: 10800
        topology: *master_3repl_1client

  fedora-27/test_installation_TestInstallWithCA_KRA_DNS1:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA_KRA_DNS1
        template: *ci-master-f27
        timeout: 10800
        topology: *master_3repl_1client

  fedora-27/test_installation_TestInstallWithCA_KRA_DNS2:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA_KRA_DNS2
        template: *ci-master-f27
        timeout: 10800
        topology: *master_3repl_1client

  fedora-27/test_installation_TestADTrustInstall:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_installation.py::TestADTrustInstall
        template: *ci-master-f27
        timeout: 10800
        topology: *master_2repl_1client

  fedora-27/test_installation_TestADTrustInstallWithDNS_KRA_ADTrust:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_installation.py::TestADTrustInstallWithDNS_KRA_ADTrust
        template: *ci-master-f27
        timeout: 10800
        topology: *master_2repl_1client

  fedora-27/test_idviews:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_idviews.py
        template: *ci-master-f27
        timeout: 7200
        topology: *ad_master_2client

  fedora-27/test_replica_promotion_TestReplicaPromotionLevel0:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_replica_promotion.py::TestReplicaPromotionLevel0
        template: *ci-master-f27
        timeout: 7200
        topology: *master_1repl

  fedora-27/test_otp:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_otp.py
        template: *ci-master-f27
        timeout: 3600
        topology: *master_1repl

  fedora-27/test_installation_TestInstallWithCA1:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA1
        template: *ci-master-f27
        timeout: 10800
        topology: *master_3repl_1client

  fedora-27/test_installation_TestInstallWithCA_DNS1:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA_DNS1
        template: *ci-master-f27
        timeout: 10800
        topology: *master_3repl_1client
